### ISSUE TITLE
Booting from USB-Stick

### ISSUE THREAD

**Issue by janbaer** [lidel/linux-on-huawei-matebook-x-2017#1]
Hello, this is not an issue, it's more a question. But at first let me say thank you, for creating this repo with the very valuable information about using Linux with the Matebook X.

My question is about booting from the usb stick. Do you need a usb-c stick or can you use a normal usb stick with using the included Matedock which has an adapter for normal usb devices?

**Comment by lidel** [comment]
Booting and installation via included Matedock works just fine 👍 

The only prerequisite is to change boot order and disable "secure boot": 

> ### Entering the Boot Menu in Matebook X
> 
> To enter the boot menu, start up your Matebook X and hold the F12 key. 
> **To install a different OS from USB you will need to disable secure boot inside the boot menu.**
>
> ### Entering BIOS in Matebook X
>
> To enter the BIOS menu, start up your Matebook X and hold the F2 key.
> 
> -- https://ersocon.net/blog/2017/7/12/matebook-x-boot-menu-and-bios
